### ISSUE TITLE
I can't launch JMC on macos catalina

### ISSUE THREAD

**Issue by navyxliu** [corretto/corretto-jmc#10]
I download the binary of macos here: 
https://github.com/corretto/corretto-jmc/releases/tag/7.1.2.1

no matter I click the icon or use open command in terminal, I get this error message. It looks like the binary hasn't be notarized. 
![Screen Shot 2020-11-13 at 9 49 11 PM](https://user-images.githubusercontent.com/2386768/99140839-1cca3e00-25fa-11eb-9260-4417fd8267b3.png)

Yes, I do have a workaround. check out here: 
https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html

**Comment by davecurrie** [comment]
The app was re-notarized with Apple and I didn't have problems opening it on a macOS Catalina machine that had never run JMC before.

Maybe this is related to the Apple OCSP outages last week -- https://9to5mac.com/2020/11/12/apple-widespread-outages-big-sur-downloads-catalina-imessage/

**Comment by navyxliu** [comment]
okay. maybe it's my OS issue. 
now I can open it. close it.
